import turtle
backg = turtle.Canvas()
win = turtle.Screen()
pen = turtle.Turtle()
pen.down()
pen.forward(100)
pen.right(120)
pen.forward(100)
pen.right(120)
pen.forward(100)
pen.right(120)
win.exitonclick()